import {GlobalColors} from './colors';

const Styles = {
  H1: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 28,
    lineHeight: 39,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H2: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 24,
    lineHeight: 33,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H3: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 20,
    lineHeight: 28,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H4: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 18,
    lineHeight: 25,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H5: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H6: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyText1: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 21,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyText2: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyText3: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 19,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyText4: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 21,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  Link: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 21,
    textDecorationLine: 'underline',
    textAlign: 'right',
    color: GlobalColors.Brand.primary,
  },
  BodyTextSmallHighlight: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 13,
    lineHeight: 17,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyTextSmall: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 17,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyTextXS: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 10,
    lineHeight: 13,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyTextLarge: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',

    fontSize: 40,
    lineHeight: 53.2,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyTextXLarge: {
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 48,
    lineHeight: 48,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
};

export default Styles;
