import {Dimensions} from 'react-native';
import {GlobalColors} from './colors';
export const {width, height} = Dimensions.get('screen');
const Styles = {
  H4: {
    fontFamily: 'Helvetica',

    fontSize: 18,
    lineHeight: 24,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H5: {
    fontFamily: 'Helvetica',
    fontStyle: 'normal',
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H6: {
    fontFamily: 'Helvetica',
    fontStyle: 'normal',
    fontSize: 18,
    lineHeight: 18,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H7: {
    fontFamily: 'Helvetica',
    fontStyle: 'normal',
    fontSize: 16,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H7Bold: {
    fontFamily: 'Helvetica',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H8: {
    fontFamily: 'Helvetica',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  H9: {
    fontFamily: 'Helvetica',
    fontStyle: 'normal',
    fontSize: 13,
    color: GlobalColors.TextColors.primary,
  },
  H10: {
    fontFamily: 'Helvetica',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 12,
    color: GlobalColors.TextColors.primary,
  },
  BodyText1: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 21,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyText2: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 20,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyText3: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 19,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyText4: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 21,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  Link: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 21,
    textDecorationLine: 'underline',
    textAlign: 'right',
    color: GlobalColors.Brand.primary,
  },
  BodyTextSmallHighlight: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 13,
    lineHeight: 17,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyTextSmall: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 17,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyTextXS: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 10,
    lineHeight: 13,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyTextLarge: {
    fontFamily: 'Segoe UI',
    fontStyle: 'normal',
    fontWeight: 'bold',

    fontSize: 40,
    lineHeight: 53.2,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
  BodyTextXLarge: {
    fontFamily: 'Inter-SemiBold',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 48,
    lineHeight: 48,
    textAlign: 'right',
    color: GlobalColors.TextColors.primary,
  },
};

export default Styles;
